//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.20 at 01:02:16 AM ICT 
//


package com.net.running_web_service;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.net.running_web_service package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.net.running_web_service
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetUserProfileResponse }
     * 
     */
    public GetUserProfileResponse createGetUserProfileResponse() {
        return new GetUserProfileResponse();
    }

    /**
     * Create an instance of {@link GetRecommendEventResponse }
     * 
     */
    public GetRecommendEventResponse createGetRecommendEventResponse() {
        return new GetRecommendEventResponse();
    }

    /**
     * Create an instance of {@link GetEventResponse }
     * 
     */
    public GetEventResponse createGetEventResponse() {
        return new GetEventResponse();
    }

    /**
     * Create an instance of {@link SetUserProfileRequest }
     * 
     */
    public SetUserProfileRequest createSetUserProfileRequest() {
        return new SetUserProfileRequest();
    }

    /**
     * Create an instance of {@link SetUserProfileResponse }
     * 
     */
    public SetUserProfileResponse createSetUserProfileResponse() {
        return new SetUserProfileResponse();
    }

    /**
     * Create an instance of {@link GetUserProfileRequest }
     * 
     */
    public GetUserProfileRequest createGetUserProfileRequest() {
        return new GetUserProfileRequest();
    }

    /**
     * Create an instance of {@link GetUserProfileResponse.RunningEvent }
     * 
     */
    public GetUserProfileResponse.RunningEvent createGetUserProfileResponseRunningEvent() {
        return new GetUserProfileResponse.RunningEvent();
    }

    /**
     * Create an instance of {@link GetRecommendEventRequest }
     * 
     */
    public GetRecommendEventRequest createGetRecommendEventRequest() {
        return new GetRecommendEventRequest();
    }

    /**
     * Create an instance of {@link GetRecommendEventResponse.RunningEvent }
     * 
     */
    public GetRecommendEventResponse.RunningEvent createGetRecommendEventResponseRunningEvent() {
        return new GetRecommendEventResponse.RunningEvent();
    }

    /**
     * Create an instance of {@link GetEventRequest }
     * 
     */
    public GetEventRequest createGetEventRequest() {
        return new GetEventRequest();
    }

    /**
     * Create an instance of {@link GetEventResponse.RunningEvent }
     * 
     */
    public GetEventResponse.RunningEvent createGetEventResponseRunningEvent() {
        return new GetEventResponse.RunningEvent();
    }

}
